### ISSUE TITLE
Unable to validate inscription when Qvitter is enabled by default

### ISSUE THREAD

**Issue by postblue** [hannesmannerheim/qvitter#64] opened 2015-01-19 15:50 UTC
When Qvitter is enabled by default (latest revision), it's impossible to validate the inscription. I have the welcome screen, I fill in all the fields, etc, but when it should display `/main/register` and create my new account, it goes back to the home page and no account has been created. It works when switching to `enabledbydefault` = false.

**Comment by hannesmannerheim** [comment] 2015-01-19 16:10
this is working on all other instances. is it on herds.eu? if you open the registrations i can test it and see that the problem is

**Comment by postblue** [comment] 2015-01-19 16:29
Yes, it's on herds.eu! I already tested it with open registrations, and it's working. It's not with invitations. If you give me an adress where to send you an invitation, I'd be glad to send it to you.

**Comment by hannesmannerheim** [comment] 2015-01-19 16:30
ah, you want "invite only". i understand! will check it out.

**Comment by postblue** [comment] 2015-01-19 16:41
Yes, I forgot to mention it, sorry.

**Comment by hannesmannerheim** [comment] 2015-01-19 17:04
fixed in https://github.com/hannesmannerheim/qvitter/commit/778d75e6f07cc9ff356356f1398751517aee2680

**Closed** 2015-01-19 17:04 UTC
Labels: bug

**Comment by postblue** [comment] 2015-01-19 17:30
Thank you!
