### ISSUE TITLE
Sometimes the "Follow" button doesn't appears

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#62] opened 2015-01-19 12:27 UTC
I have a help account on Quitter.zone and sometimes, users tell me that they haven't been able to see this button.

**Comment by hannesmannerheim** [comment] 2015-01-19 12:54
it's a known issue i've heard from users on quitter.no. very mysterious! the may appear if they temporarily change the browser window witdh to a narrow window... 

maybe it's a specific browser causing it, maybe it's a browser plugin?

**Comment by moshpirit** [comment] 2015-01-19 13:15
I don't know, it works fine for me

**Comment by hannesmannerheim** [comment] 2015-01-19 13:22
keep your eyes open for any clues as to which browser/setting is causing this!

**Comment by moshpirit** [comment] 2015-01-19 13:45
Sure! I'll let you know!

**Comment by postblue** [comment] 2015-01-19 19:21
To make it clear, is it about the `follow-button` not displayed in `user-actions` of a `popup-external-profile`?

![](http://i.imgur.com/ny7WM4j.png)

**Comment by moshpirit** [comment] 2015-01-19 19:26
Exactly, please, in what conditions you found this bug? Every information it's appreciated

**Comment by hannesmannerheim** [comment] 2015-01-19 19:43
here's an old thread about this issue https://quitter.no/notice/73543

**Comment by hannesmannerheim** [comment] 2015-01-19 20:01
@postblue can you try the latest commit and see if it fixes it? it's just a wild guess, since i can't reproduce it

**Comment by postblue** [comment] 2015-01-19 20:37
@moshpirit Just clicking a @ mention in my timeline (heirds.eu/postblue/all), what displays the remote profile (and I like how it does).

@hannesmannerheim Let's do this. "cd /var/www/herds; git pull -u; php scripts/upgrade.php; cd /var/www/herds/plugins/Qvitter; git pull -u"

![](http://i.imgur.com/q6Cs9l9.png)

No chance. :/ Using Firefox 35.0.

**Comment by hannesmannerheim** [comment] 2015-01-19 20:49
@postblue how about now?

**Comment by postblue** [comment] 2015-01-19 21:23
Unfortunately, not yet.

**Comment by hannesmannerheim** [comment] 2015-01-19 21:25
ok :/ thanks for testing

**Comment by hannesmannerheim** [comment] 2015-01-19 21:25
i'm out of ideas now..

**Comment by postblue** [comment] 2015-01-19 21:25
No problem, it's just one git pull, clear cache, CTRL F5.

**Comment by moshpirit** [comment] 2015-01-21 00:46
- SO: Windows 7 (64 bits)
- Web browser: Waterfox 34.0.1
- Extensions/plugins: Adblock Edge (using Ultimate List by fanboyz) NoScript, Request Policy and Self-Desctructing Cookies
- User: [librepensador on quitter.es](https://quitter.es/notice/65356)

**Comment by postblue** [comment] 2015-01-21 15:48
I totally forgot to test without AdBlock! Because it's named `follow-button`, it's hidden by one of my lists (Fanboy's Social Blocking List, I think). It's working on Herds if I deactivate the extension for the domain.

**Comment by hannesmannerheim** [comment] 2015-01-21 16:13
great!! thanks! i'll rename it to something else

**Comment by hannesmannerheim** [comment] 2015-01-26 19:10
fixed in https://github.com/hannesmannerheim/qvitter/commit/5ffe3faf96590fbfa957de91d7a23585c03594a8

**Closed by hannesmannerheim** 2015-01-26 19:10 UTC
Labels: bug
