### ISSUE TITLE
Copying queets as rich text deletes hashtags

### ISSUE THREAD

**Issue by gordon-morehouse** [hannesmannerheim/qvitter#137] opened 2015-03-17 17:51 UTC
1. Compose a queet which contains some hashtags and maybe some URLs
2. Post the queet.
3. Copy it in a rich-text-capable browser such as Chromium
4. Paste it.

WHAT ACTUALLY HAPPENS:

The hash mark (#) is deleted from in front of the hashtags, and the hashtags appear as links.

WHAT SHOULD HAPPEN:

The hash mark (#) should not be deleted from in front of the hashtags; possibly, hashtags should not appear as links.

**Comment by hannesmannerheim** [comment] 2015-03-17 19:27
this is because @ and # is removed and inserted as pseudo-elements with css. the point of that was to solve some issues with rtl-support. i was aware of the downside you describe. therefor i'm marking this as an enhancement not a bug.

**Closed** 2015-06-16 23:38 UTC
Labels: enhancement
