### ISSUE TITLE
Ghost notification in firefox (Notification reset button bug)

### ISSUE THREAD

**Issue by lulivi** [hannesmannerheim/qvitter#102] opened 2015-02-07 10:20 UTC
I see a notification and go to https://quitter.es/luvo/notifications

![1](https://cloud.githubusercontent.com/assets/10894592/6091736/9982742a-aeba-11e4-8342-1db00c41b270.png)
 |
 |
V
It disappears.

![2](https://cloud.githubusercontent.com/assets/10894592/6091737/9d7828a4-aeba-11e4-87d8-22648b9e1b70.png)

Then go to https://quitter.es/main/all and the notification come up again.

![3](https://cloud.githubusercontent.com/assets/10894592/6091738/a071b61a-aeba-11e4-820f-d53ea0bbccac.png)

**Comment by mmn** [comment] 2015-02-07 10:37
So I think the feature request here is the "reset my notification count". I know it would be neat to have on my instance where I generally run the "classic" view but when going mobile I use the Qvitter frontend. :)

**Comment by hannesmannerheim** [comment] 2015-02-07 11:05
@lulivi i'm curious though. what happens if you try to scroll down as far as possible on the notification page?

**Comment by soulchainer** [comment] 2015-02-07 11:32
Just a qualification: it isn't a only firefox bug. I'm suffering this from about a week, just after this perro@quitter.es notification https://quitter.es/notice/158702 (I guess that it can be related to changes in the nightly he pushed that afternoon), in all web browsers (Firefox, Midori and Chromium, in my case).

**Comment by lulivi** [comment] 2015-02-07 11:33
It does nothing.

![1](https://cloud.githubusercontent.com/assets/10894592/6091936/c1446392-aec4-11e4-9000-582fb408d74d.png)

I realized that there is one notification marked:

![2](https://cloud.githubusercontent.com/assets/10894592/6091938/db00ab6a-aec4-11e4-86d1-3dc94d2a0d23.png)

But I can't "read". It persist.

![3](https://cloud.githubusercontent.com/assets/10894592/6091944/16cf641a-aec5-11e4-90c7-bd4c2a5fa985.png)

**Comment by hannesmannerheim** [comment] 2015-02-07 11:41
interesting, so when switching away from notifications and back to notifications, that queet from 1:10 6 feb is still marked as unread?

**Comment by lulivi** [comment] 2015-02-07 11:42
Yes, that's it.

**Comment by hannesmannerheim** [comment] 2015-02-07 11:49
i think we need @mmn's expertise here. 

all notifications displayed should be marked seen. can it have anything to do with this change you did @mmn? https://github.com/hannesmannerheim/qvitter/commit/5d83ff5b34d7f6be53139e9582c2d4163eb47d42

**Comment by hannesmannerheim** [comment] 2015-02-07 11:50
(no rush here @mmn!)

**Comment by hannesmannerheim** [comment] 2015-02-07 11:54
another theory: maybe, for some reason, $notification->is_seen is null instead of 0 for that notice https://quitter.es/notice/185059. you might want to check that in the db @mmn

**Comment by lulivi** [comment] 2015-02-07 11:57
It is so strange, isn't it? Only that notification.

**Comment by hannesmannerheim** [comment] 2015-02-07 11:59
very. but the notice_id field in that table has been randomly null for mysterious reasons before, so maybe sometimes the is_seen field becomes null too.

**Comment by mmn** [comment] 2015-02-08 09:23
I'm on it. Found some in my own notifications which I can experiment with.

**Comment by mmn** [comment] 2015-02-08 09:47
As far as I can tell, the query is executed and correct, so if it is run - it would do the right thing. But maybe it is reset by something that - for some reason - sets is_seen to 0 again?

Maybe a MySQL transaction ROLLBACK (or missing 'COMMIT'?).

**Comment by mmn** [comment] 2015-02-08 09:56
What the heck. Now that I ran the COMMIT I can't recreate the issue. @lulivi are your notifications working as intended now too?

**Comment by lulivi** [comment] 2015-02-08 10:24
Notification continues trolling me.

**Comment by hannesmannerheim** [comment] 2015-02-08 13:11
i don't understand this fully. should i add a $notification->query('COMMIT') somewhere?

**Comment by mmn** [comment] 2015-02-08 13:16
Hannes Mannerheim <notifications@github.com> skrev: (8 februari 2015 14:11:04 CET)
>i don't understand this fully. should i add a
>$notification->query('COMMIT') somewhere?

No, you haven't started any transactions in Qvitter so it's somewhere in GNU social. I think it's in lib/util.php around the session cookie stuff for rememberme.

I've got one test to run on quitter.es


-- 
Mikael Nordfeldth
XMPP/mail: mmn@hethane.se

**Comment by mmn** [comment] 2015-02-08 14:24
The quitter.es specific issue with the never-marked-as-seen notification is now fixed. Thanks, folks.

Now I think the issue is the actual reset-notification-button.

**Comment by knuthollund** [comment] 2015-02-08 21:57
What did the trick @mmn ? Got a report on this for q.no as well. https://quitter.no/notice/229696

**Comment by hannesmannerheim** [comment] 2015-02-08 22:00
i think it was this https://gitorious.org/social/mainline/commit/59bbc81c4b71dbfc37f9a2058012bd5c342c3faa – right @mmn? :)

**Comment by knuthollund** [comment] 2015-02-08 22:02
Ok tx. @hannesmannerheim - just waiting for confirmation from @mmn

**Comment by JasterTDC** [comment] 2015-02-08 22:03
I have the same problem, but notifications get stuck in 7
![captura de pantalla de 2015-02-08 23 02 52](https://cloud.githubusercontent.com/assets/6804441/6098674/b546beaa-afe6-11e4-97c3-c337038cade6.png)

**Comment by mmn** [comment] 2015-02-08 22:08
@knuthollund @hannesmannerheim @JasterTDC yes, https://gitorious.org/social/mainline/commit/59bbc81c4b71dbfc37f9a2058012bd5c342c3faa did the trick

Pushed the nightly branch to master and 1.1.x again, so we don't leave bugs like these in those branches. If you're updating the master from just some day ago, you shouldn't have to do upgrade.php or restart the queuedaemons or anything, but it's still good practice to do it. But I think a git pull is enough.

**Comment by knuthollund** [comment] 2015-02-08 22:10
Ok tx.

**Comment by knuthollund** [comment] 2015-02-08 22:17
@JasterTDC - could you test your issue again and report back if the notification number is reset after reading them?

**Comment by knuthollund** [comment] 2015-02-08 23:01
Ok - the fix did the trick for @JasterTDC too.

**Closed** 2015-02-24 21:52 UTC
